### ISSUE TITLE
Delete files from other users?

### ISSUE THREAD

**Issue by vincentmorneau** [drewminns/slack#18]
As a team owner or an admin, should I be able to delete files from other people?

Our team has grown quite large and even if I delete my own files and those from public channels, we still get the file limit warning.

Any insight?

**Comment by bobziroll** [comment]
Our team has been brainstorming over this, and from what I can find @vincentmorneau, there's no way to delete other people's files if they're shared in private channels or DMs. And thinking about the number of private channels and the web of DMs, that's probably where a majority of the files exist. We resorted to posting a message in the general channel to have people go through their files and delete as many as they can.

**Comment by vincentmorneau** [comment]
Thank you.
