### ISSUE TITLE
Getting white screen when trying to login to slack

### ISSUE THREAD

**Issue by chrisyerkes** [drewminns/slack#19]
Hi, first of all, just want to say my team thanks you from the bottom of our hearts. We use your tool every time we get up to the file limit and love it.

We went to the app today and when we hit the login to slack button, we are presented with a white screen.

Just wanted to make you aware. Thank you again for the great tool!

**Comment by drewminns** [comment]
Hey! I think it had something to do with my hosting. Try doing the full http://www.slackdeletron.com/ and it should work!

I'll make an update when I can!

**Comment by chrisyerkes** [comment]
Thanks!
