### ISSUE TITLE
Undefined because Promise incomplete

### ISSUE THREAD

**Issue by me0wday** [drewminns/slack#2]
The code `if (action.payload.data.ok)` breaks when the Promise is in a pending state.

Unsure how to fix this using redux-promise.

**Comment by drewminns** [comment]
Will look into it. Thanks!

**Comment by drewminns** [comment]
Should be handled in latest commit. Redux can't handle additional properties on the payload. Who knew ¯_(ツ)_/¯

Take a peek and let me know!

**Comment by drewminns** [comment]
Closing this assuming that it's taken care of now.
