### ISSUE TITLE
Where's delete everything?

### ISSUE THREAD

**Issue by rohapa** [drewminns/slack#3]
Where's delete everything?

**Comment by drewminns** [comment]
It's a v2 step. Unfortunately, it's an issue with separate API calls for each file. I need to create a better experience to handle bulk deletion and if there are any failures.

**Comment by drewminns** [comment]
I lied. I put it in. I hope it's working, there were some issues with Redux-Promise resolving the payload when there was another property on the object. Hopefully resolved. Can you let me know if there are any problems??

**Comment by drewminns** [comment]
Added and closing
