### ISSUE TITLE
Doesn't delete public channel files

### ISSUE THREAD

**Issue by fitchd** [drewminns/slack#8]
It appears to only delete files from Direct Messages, not public channels. I deleted everything it could find, which was over 100 files, and Slack is still telling our team we are over our storage limit. It did not remove images and files from the general channel.

**Comment by drewminns** [comment]
@fitchd Unfortunately the API that Slack offers only allows you to delete files that have uploaded. You have to ask every user on your team to use the tool and delete their files. I'm guessing that Slack doesn't allow this functionality due to privacy issues.

**Comment by fitchd** [comment]
@drewminns Gotchya. Thanks for getting back to me. Love your tool regardless!
